DROP TABLE PLAYER;
DROP TABLE TEAM;
DROP TABLE MATCH;
DROP SEQUENCE SEQ_PLAYER;
DROP SEQUENCE SEQ_TEAM;
DROP SEQUENCE SEQ_MATCH;
DROP SEQUENCE SEQ_PLAYER;
DROP SEQUENCE SEQ_TEAM;
DROP SEQUENCE SEQ_MATCH;

CREATE SEQUENCE SEQ_PLAYER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TEAM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATCH START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TABLE PLAYER (
    PLAYER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    TEAM VARCHAR2(100),
    POSITION VARCHAR2(50),
    AGE NUMBER,
    GOALS NUMBER DEFAULT 0,
    ASSISTS NUMBER DEFAULT 0,
    CREATED_AT DATE DEFAULT SYSDATE
);



CREATE TABLE TEAM (
    TEAM_ID NUMBER PRIMARY KEY,
    TEAM_NAME VARCHAR2(100) UNIQUE NOT NULL,
    CITY VARCHAR2(100),
    COACH VARCHAR2(100),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE MATCH (
    MATCH_ID NUMBER PRIMARY KEY,
    MATCH_DATE DATE NOT NULL,
    HOME_TEAM VARCHAR2(100),
    AWAY_TEAM VARCHAR2(100),
    HOME_SCORE NUMBER DEFAULT 0,
    AWAY_SCORE NUMBER DEFAULT 0,
    STADIUM VARCHAR2(100),
    CREATED_AT DATE DEFAULT SYSDATE
);

